//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarzinTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_PersonelsInfo
    {
        public int EntityCode { get; set; }
        public int CategoryCode { get; set; }
        public int RaitingHits { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<bool> IsPreNote { get; set; }
        public bool Locked { get; set; }
        public bool LocalLock { get; set; }
        public int LocalLockUserCode { get; set; }
        public int LocalLockRoleID { get; set; }
        public int LockUserCode { get; set; }
        public int LockRoleID { get; set; }
        public string FieldsStatus { get; set; }
        public bool IsPrivateSearch { get; set; }
        public int PrivateSearchUserCode { get; set; }
        public int PrivateSearchRoleID { get; set; }
        public Nullable<System.DateTime> LastSignatureDate { get; set; }
        public string EntityNumber { get; set; }
        public int NumberOfCopies { get; set; }
        public string Version { get; set; }
        public int OriginalVersionCode { get; set; }
        public bool IsSigned { get; set; }
        public int SecurityLevelCode { get; set; }
        public bool IsConfirm { get; set; }
        public bool IsActive { get; set; }
        public int FirstEntityCode { get; set; }
        public string From { get; set; }
        public string ImportEntityNumber { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string ImportMethod { get; set; }
        public string ImportDesc { get; set; }
        public string ImportOriginNO { get; set; }
        public Nullable<System.DateTime> ImportOriginDate { get; set; }
        public string NOPgAttached { get; set; }
        public string To { get; set; }
        public string ExportEntityNumber { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string ExportMethod { get; set; }
        public string ExportDesc { get; set; }
        public Nullable<int> ImportIndicatorID { get; set; }
        public Nullable<int> ExportIndicatorID { get; set; }
        public Nullable<int> ImportRegisterID { get; set; }
        public Nullable<int> ImportRegisterRoleID { get; set; }
        public Nullable<int> ExportRegisterID { get; set; }
        public Nullable<int> ExportRegisterRoleID { get; set; }
        public string DocType { get; set; }
        public string DocSubject { get; set; }
        public string DocKeywords { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ImportPriority { get; set; }
        public Nullable<int> ExportPriority { get; set; }
        public int CreatorID { get; set; }
        public int CreatorRoleID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string PersonelID { get; set; }
        public Nullable<int> Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string NationalID { get; set; }
        public Nullable<int> Project { get; set; }
        public Nullable<int> Post { get; set; }
        public Nullable<int> Job { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EducationDegree { get; set; }
        public Nullable<bool> Status { get; set; }
        public string GenderText { get; set; }
        public string ProjectText { get; set; }
        public string StartDateText { get; set; }
    }
}
