//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarzinTools.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eOrganizationEntities1 : DbContext
    {
        public eOrganizationEntities1()
            : base("name=eOrganizationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entity_BaseInfo> Entity_BaseInfo { get; set; }
        public virtual DbSet<Entity_PersonelsInfo> Entity_PersonelsInfo { get; set; }
        public virtual DbSet<Entity_PersonsPerform> Entity_PersonsPerform { get; set; }
    }
}
